name: Deploy React App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env file
        run: |
          echo "REACT_APP_KAKAO_API_KEY=${{ secrets.REACT_APP_KAKAO_API_KEY }}" >> .env
          echo "REACT_APP_NAVER_API_KEY=${{ secrets.REACT_APP_NAVER_API_KEY }}" >> .env
          echo "REACT_APP_KAKAOMAP_API_KEY=${{ secrets.REACT_APP_KAKAOMAP_API_KEY }}" >> .env
          echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> .env
          echo "REACT_APP_FIREBASE_API_ID=${{ secrets.REACT_APP_FIREBASE_API_ID }}" >> .env
          echo "REACT_APP_FIREBASE_MESSAGESENDER_ID=${{ secrets.REACT_APP_FIREBASE_MESSAGESENDER_ID }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build
